# travis file
# https://docs.travis-ci.com/user/customizing-the-build

notifications:
  email: false

branches:
  except:
    - release

language: node_js

node_js:
  - 8.4.0

env:
  - CXX=g++-4.8 NODE_ENV=production

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - graphicsmagick

cache:
  directories:
    # パッケージをキャッシュすると本来は動かないはずなのに動いてしまう
    # 場合があり危険なのでキャッシュはしない:
    #- node_modules

services:
  - mongodb
  - redis-server

before_script:
  # Travisはproduction環境なので(10行目により)、
  # npm install しただけでは devDependencies はインストールされないので、
  # --only=dev オプションを付けてそれらもインストールされるようにする:
  - npm install --only=dev

  # 設定ファイルを設定
  - mkdir ./.config
  - cp ./.travis/default.yml ./.config
  - cp ./.travis/test.yml ./.config

  - npm run build

after_success:
  # リリース
  - chmod u+x ./.travis/release.sh
  - if [ $TRAVIS_BRANCH = "master" ] && [ $TRAVIS_PULL_REQUEST = "false" ]; then ./.travis/release.sh; else echo "Skipping releasing task"; fi
