# travis file
# https://docs.travis-ci.com/user/customizing-the-build

language: node_js

node_js:
  - "7.6.0"

env:
  - CXX=g++-4.8 NODE_ENV=production

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - graphicsmagick

cache:
  directories:
    - node_modules

services:
  - mongodb
  - redis-server

before_script:
  - mkdir ./.config
  - cp ./.travis/default.yml ./.config
  - cp ./.travis/test.yml ./.config
  - npm run build

after_success:
  - ./.travis/release.sh
