# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: 10.1.0

build: off

install:
  # Update Node.js
  # 標準で入っている Node.js を更新します (2014/11/13 時点では、v0.10.32 が標準)
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - node --version

  # Update NPM
  - npm install -g npm
  - npm --version

  # Update node-gyp
  # 必須! node-gyp のバージョンを上げないと、ネイティブモジュールのコンパイルに失敗します
  - npm install -g node-gyp

  - npm install

init:
  # git clone の際の改行を変換しないようにします
  - git config --global core.autocrlf false

test_script:
  - npm test
