version: "3"

# このconfigは、 dockerでMisskey本体を起動せず、 redisとpostgresql などだけを起動します

services:
  dragonfly:
    restart: always
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ulimits:
      memlock: -1
    environment:
      DFLY_snapshot_cron: '* * * * *'
      DFLY_version_check: false
      DFLY_tcp_backlog: 2048
      DFLY_lock_on_hashtags: true
      DFLY_pipeline_squash: 0
      DFLY_multi_exec_squash: false
      DFLY_conn_io_threads: 4
      DFLY_epoll_file_threads: 4
      DFLY_proactor_threads: 4
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data

  db:
    restart: always
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    env_file:
      - .config/docker.env
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      retries: 20

#  meilisearch:
#    restart: always
#    image: getmeili/meilisearch:v1.3.4
#    environment:
#      - MEILI_NO_ANALYTICS=true
#      - MEILI_ENV=production
#    env_file:
#      - .config/meilisearch.env
#    volumes:
#      - ./meili_data:/meili_data

