apiVersion: apps/v1
kind: Deployment
metadata:
  name: misskey
spec:
  selector:
    matchLabels:
      app: misskey
  replicas: 1
  template:
    metadata:
      labels:
        app: misskey
    spec:
      containers:
      - name: misskey
        image: okteto.dev/misskey:${OKTETO_GIT_COMMIT}
        ports:
        - containerPort: 8080
