name: API report (misskey.js)

on: [push, pull_request]

jobs:
  report:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm --filter misskey-js build

      - name: Check files
        run: ls packages/misskey-js/built

      - name: API report
        run: pnpm --filter misskey-js api-prod

      - name: Show report
        if: always()
        run: cat packages/misskey-js/temp/misskey-js.api.md
