name: Check the description in CHANGELOG.md

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  check-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout base
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.base_ref }}
      - name: Extract CHANGELOG-base.md
        run: cp CHANGELOG.md CHANGELOG-base.md

      - name: Checkout head
        run: git checkout refs/pull/${{ github.event.number }}/merge
      - name: Extract CHANGELOG-head.md
        run: cp CHANGELOG.md CHANGELOG-head.md

      - name: Move to Checker directory
        run: mv CHANGELOG-*.md scripts/changelog-checker

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.1
        with:
          node-version-file: '.node-version'

      - name: Setup Checker
        run: npm i
        working-directory: scripts/changelog-checker
      - name: Run Checker
        run: npm run run
        working-directory: scripts/changelog-checker
