name: ã†ã™ã‚†ããƒ¼è‡ªå‹•ãƒ‡ãƒ—ãƒ­ã‚¤

on:
  pull_request:
    branches:
      - usuyukey-master@v13
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo "STARTğŸš€"
            echo "${{ secrets.SERVER_USER_PASSWORD }}" | sudo -S systemctl stop misskey
            sudo -u misskey sh -c 'cd /home/misskey/usuyukey && git fetch'
            sudo -u misskey sh -c 'cd /home/misskey/usuyukey && git reset --hard origin/usuyukey-master@v13'
            sudo -u misskey sh -c 'cd /home/misskey/usuyukey && git submodule update --init --recursive'
            sudo -u misskey sh -c 'cd /home/misskey/usuyukey && sed -i -e "s/\(\"version\": \".*\)\(\"\)/\\1-usuyukey-${{ secrets.USUYUKEY_VERSION }}\2/" package.json'
            sudo -u misskey sh -c 'cd /home/misskey/usuyukey && /home/misskey/.asdf/shims/pnpm install'
            sudo -u misskey sh -c 'cd /home/misskey/usuyukey && /home/misskey/.asdf/shims/pnpm clean'
            sudo -u misskey sh -c 'cd /home/misskey/usuyukey && NODE_ENV=production /home/misskey/.asdf/shims/pnpm build'
            sudo -u misskey sh -c 'cd /home/misskey/usuyukey && NODE_ENV=production /home/misskey/.asdf/shims/pnpm migrate'
            sudo systemctl restart misskey
            echo "DONEğŸ¥³"
